#!/bin/bash
python3 ../main.py --dir /data2/hhjung/Gradient/Noise10/Rev_T/dotone --noise-rate 0.1 --grad T --gpu 1 --lr 1e-4 --layer 20 --low=-0.1 --high=1. 1> /dev/null &
python3 ../main.py --dir /data2/hhjung/Gradient/Noise20/Rev_T/dotone --noise-rate 0.2 --grad T --gpu 4 --lr 1e-4 --layer 20 --low=-0.1 --high=1. 1> /dev/null
