#!/bin/bash
python3 ../main.py --dir /data2/hhjung/Gradient4/Noise10/Dist40 --dist 0.4 --noise-rate 0.1 --grad T --gpu 3 --lr 1e-4 --layer 8 --low=-0.1 --high=1. 1> /dev/null &&
python3 ../main.py --dir /data2/hhjung/Gradient4/Noise20/Dist40 --dist 0.4 --noise-rate 0.2 --grad T --gpu 3 --lr 1e-4 --layer 8 --low=-0.1 --high=1. 1> /dev/null &&
python3 ../main.py --dir /data2/hhjung/Gradient4/Noise30/Dist40 --dist 0.4 --noise-rate 0.3 --grad T --gpu 3 --lr 1e-4 --layer 8 --low=-0.1 --high=1. 1> /dev/null &&
