#!/bin/bash
python3 ../main.py --dir /data2/hhjung/Norm3/P3/All/group4/batch16 --Mode 2 -b 16 --Method P3 --group 4 --gpu 7 --layer 2 1> /dev/null &&
python3 ../main.py --dir /data2/hhjung/Norm3/P3/All/group4/batch32 --Mode 2 -b 32 --Method P3 --group 4 --gpu 7 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm3/P3/All/group4/batch64 --Mode 2 -b 64 --Method P3 --group 4 --gpu 7 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm3/P3/All/group4/batch128 --Mode 2 -b 128 --Method P3 --group 4 --gpu 7 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm3/P3/All/group16/batch16 --Mode 2 -b 16 --Method P3 --group 16 --gpu 7 --layer 2 1> /dev/null &&
python3 ../main.py --dir /data2/hhjung/Norm3/P3/All/group16/batch32 --Mode 2 -b 32 --Method P3 --group 16 --gpu 7 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm3/P3/All/group16/batch64 --Mode 2 -b 64 --Method P3 --group 16 --gpu 7 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm3/P3/All/group16/batch128 --Mode 2 -b 128 --Method P3 --group 16 --gpu 7 --layer 2 1> /dev/null
