#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/TypeC/Scene3/0.1 -w 0.1 0.4 --gamma 0.1 -mi 250 300 --epoch4 350 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/TypeC/Scene3/0.2 -w 0.1 0.4 --gamma 0.2 -mi 250 300 --epoch4 350 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/TypeC/Scene3/0.3 -w 0.1 0.4 --gamma 0.3 -mi 250 300 --epoch4 350 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/TypeC/Scene3/0.4 -w 0.1 0.4 --gamma 0.4 -mi 250 300 --epoch4 350 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/TypeC/Scene3/0.5 -w 0.1 0.4 --gamma 0.5 -mi 250 300 --epoch4 350 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/TypeC/Scene3/0.6 -w 0.1 0.4 --gamma 0.6 -mi 250 300 --epoch4 350 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/TypeC/Scene3/0.7 -w 0.1 0.4 --gamma 0.7 -mi 250 300 --epoch4 350 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/TypeC/Scene3/0.8 -w 0.1 0.4 --gamma 0.8 -mi 250 300 --epoch4 350 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/TypeC/Scene3/0.9 -w 0.1 0.4 --gamma 0.9 -mi 250 300 --epoch4 350 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 6 1> /dev/null 2> /dev/null