#!/bin/bash
python3.5 ../main.py --dir semi/style/2 -s 1 1 0 0 0 0 0 0 --style 2 --case 1 --gpu 0 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir semi/style/4 -s 1 1 1 1 0 0 0 0 --style 4 --case 1 --gpu 0 1> /dev/null 2> /dev/null