#!/bin/bash
python3.5 ../main.py --dir semi/loc/3 -s 0 0 0 0 1 1 0 0 --style 0 --case 0 --gpu 3 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir semi/loc/4 -s 0 0 0 0 0 0 1 1 --style 0 --case 0 --gpu 3 1> /dev/null 2> /dev/null
