#!/bin/bash
(python3.5 ../main.py --dir style/2 -s 1 1 0 0 0 0 0 0 --style 2 --case 1 --gpu 0 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir style/4 -s 1 1 1 1 0 0 0 0 --style 4 --case 1 --gpu 0 1> /dev/null 2> /dev/null ) &
(python3.5 ../main.py --dir style/6 -s 1 1 1 1 1 1 0 0 --style 6 --case 1 --gpu 1 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir style/8 -s 1 1 1 1 1 1 1 1 --style 8 --case 1 --gpu 1 1> /dev/null 2> /dev/null ) &
(python3.5 ../main.py --dir loc/1 -s 1 1 0 0 0 0 0 0 --style 0 --case 0 --gpu 2 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir loc/2 -s 0 0 1 1 0 0 0 0 --style 0 --case 0 --gpu 2 1> /dev/null 2> /dev/null ) &
(python3.5 ../main.py --dir loc/3 -s 0 0 0 0 1 1 0 0 --style 0 --case 0 --gpu 3 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir loc/4 -s 0 0 0 0 0 0 1 1 --style 0 --case 0 --gpu 3 1> /dev/null 2> /dev/null ) &
(python3.5 ../main.py --dir loc/top -s 1 0 1 0 1 0 1 0 --style 0 --case 0 --gpu 4 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir loc/bot -s 0 1 0 1 0 1 0 1 --style 0 --case 0 --gpu 4 1> /dev/null 2> /dev/null ) &
(python3.5 ../main.py --dir type/0 -s 0 0 0 0 0 0 0 0 --style 0 --case 0 --gpu 5 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir type/1 -s 1 1 1 1 1 1 1 1 --style 0 --case 0 --gpu 5 1> /dev/null 2> /dev/null ) &
(python3.5 ../main.py --dir type/2 -s 2 2 2 2 2 2 2 2 --style 0 --case 0 --gpu 6 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir type/3 -s 3 3 3 3 3 3 3 3 --style 0 --case 0 --gpu 6 1> /dev/null 2> /dev/null ) &
