#!/bin/bash
python3.5 ../main.py --dir semi/type/2 -s 2 2 2 2 2 2 2 2 --style 0 --case 0 --gpu 6 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir semi/type/3 -s 3 3 3 3 3 3 3 3 --style 0 --case 0 --gpu 6 1> /dev/null 2> /dev/null
