#!/bin/bash
python3.5 ../main.py --dir semi/loc/1 -s 1 1 0 0 0 0 0 0 --style 0 --case 0 --gpu 2 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir semi/loc/2 -s 0 0 1 1 0 0 0 0 --style 0 --case 0 --gpu 2 1> /dev/null 2> /dev/null
