#!/bin/bash
python3.5 ../main.py --dir semi/loc/top -s 1 0 1 0 1 0 1 0 --style 0 --case 0 --gpu 4 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir semi/loc/bot -s 0 1 0 1 0 1 0 1 --style 0 --case 0 --gpu 4 1> /dev/null 2> /dev/null