#!/bin/bash
python3.5 ../main.py --dir semi/type/0 -s 0 0 0 0 0 0 0 0 --style 0 --case 0 --gpu 5 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir semi/type/1 -s 1 1 1 1 1 1 1 1 --style 0 --case 0 --gpu 5 1> /dev/null 2> /dev/null
