#!/bin/bash
python3.5 ../main.py --dir semi/style/6 -s 1 1 1 1 1 1 0 0 --style 6 --case 1 --gpu 1 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir semi/style/8 -s 1 1 1 1 1 1 1 1 --style 8 --case 1 --gpu 1 1> /dev/null 2> /dev/null