#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.00001/n0.0/M --lr 0.00001 --noise-rate 0.0 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.00001/n0.1/M --lr 0.00001 --noise-rate 0.1 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.00001/n0.2/M --lr 0.00001 --noise-rate 0.2 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.00001/n0.3/M --lr 0.00001 --noise-rate 0.3 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.00001/n0.4/M --lr 0.00001 --noise-rate 0.4 --gpu 3 1> /dev/null 2> /dev/null