#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/10.30.0 --m 4 --gpu 0 --epoch1 10 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/20.30.0 --m 4 --gpu 0 --epoch1 20 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/30.30.0 --m 4 --gpu 0 --epoch1 30 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/40.30.0 --m 4 --gpu 0 --epoch1 40 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/50.30.0 --m 4 --gpu 0 --epoch1 50 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/60.30.0 --m 4 --gpu 0 --epoch1 60 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/70.30.0 --m 4 --gpu 0 --epoch1 70 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/80.30.0 --m 4 --gpu 0 --epoch1 80 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/90.30.0 --m 4 --gpu 0 --epoch1 90 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m4/100.30.0 --m 4 --gpu 0 --epoch1 100 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null
