#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.01/n0.0/S --lr 0.01 --noise-rate 0.0 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.01/n0.1/S --lr 0.01 --noise-rate 0.1 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.01/n0.2/S --lr 0.01 --noise-rate 0.2 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.01/n0.3/S --lr 0.01 --noise-rate 0.3 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/lr0.01/n0.4/S --lr 0.01 --noise-rate 0.4 --gpu 4 1> /dev/null 2> /dev/null