#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE/noise2 --noise-rate 0.2 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE/noise3 --noise-rate 0.3 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE/noise4 --noise-rate 0.4 --gpu 4 1> /dev/null 2> /dev/null