#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE/t1_2 --noise-rate 0.2 --gpu 6 --t1 0. 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE/t1_3 --noise-rate 0.3 --gpu 6 --t1 0. 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE/t1_4 --noise-rate 0.4 --gpu 6 --t1 0. 1> /dev/null 2> /dev/null
