#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/10.30.0 --m 6 --gpu 2 --epoch1 10 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/20.30.0 --m 6 --gpu 2 --epoch1 20 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/30.30.0 --m 6 --gpu 2 --epoch1 30 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/40.30.0 --m 6 --gpu 2 --epoch1 40 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/50.30.0 --m 6 --gpu 2 --epoch1 50 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/60.30.0 --m 6 --gpu 2 --epoch1 60 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/70.30.0 --m 6 --gpu 2 --epoch1 70 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/80.30.0 --m 6 --gpu 2 --epoch1 80 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/90.30.0 --m 6 --gpu 2 --epoch1 90 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_ResNet/ResNet18/Step/m6/100.30.0 --m 6 --gpu 2 --epoch1 100 --epoch2 30 --epoch3 0 1> /dev/null 2> /dev/null