#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE/noise0 --noise-rate 0.0 --gpu 0 1> /dev/null 2> noise0 &&
python3 ../main.py --dir /data2/hhjung/NAE/noise1 --noise-rate 0.1 --gpu 0 1> /dev/null 2> noise1
