#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE/t2_0 --noise-rate 0.0 --gpu 3 --t2 0. 1> /dev/null 2> t2_0 &&
python3 ../main.py --dir /data2/hhjung/NAE/t2_1 --noise-rate 0.1 --gpu 3 --t2 0. 1> /dev/null 2> t2_1
