#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE/only2 --noise-rate 0.2 --gpu 5 --t0 0. 1> /dev/null 2>/dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE/only3 --noise-rate 0.3 --gpu 5 --t0 0. 1> /dev/null 2>/dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE/only4 --noise-rate 0.4 --gpu 5 --t0 0. 1> /dev/null 2>/dev/null
