#!/bin/bash
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/func_3/n0.0 --noise-rate 0.0 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/func_3/n0.1 --noise-rate 0.1 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/func_3/n0.2 --noise-rate 0.2 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/func_3/n0.3 --noise-rate 0.3 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /data2/hhjung/NAE_Gaussian/func_3/n0.4 --noise-rate 0.4 --gpu 3 1> /dev/null 2> /dev/null