#!/bin/bash
python3 ../main.py --dir FA/IN_case0 -w 0.0 1.0 --case 0 --gpu 0 1> /dev/null 2> /dev/null &
python3 ../main.py --dir FA/IN_case1 -w 0.0 1.0 --case 1 --gpu 1 1> /dev/null 2> /dev/null &
python3 ../main.py --dir FA/IN_case2 -w 0.0 1.0 --case 2 --gpu 2 1> /dev/null 2> /dev/null &
python3 ../main.py --dir FA/IN_case3 -w 0.0 1.0 --case 3 --gpu 3 1> /dev/null 2> /dev/null &
python3 ../main.py --dir FA/BNIN_case0 -w 0.5 0.5 --case 0 --gpu 4 1> /dev/null 2> /dev/null &
python3 ../main.py --dir FA/BNIN_case1 -w 0.5 0.5 --case 1 --gpu 5 1> /dev/null 2> /dev/null &
python3 ../main.py --dir FA/BNIN_case2 -w 0.5 0.5 --case 2 --gpu 6 1> /dev/null 2> /dev/null &
python3 ../main.py --dir FA/BNIN_case3 -w 0.5 0.5 --case 3 --gpu 7 1> /dev/null 2> /dev/null