#!/bin/bash
python3.5 ../main.py --dir type/2 -w 0.0 -s 2 2 2 2 2 2 2 2 --style 0 --gpu 6 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir type/3 -w 0.0 -s 3 3 3 3 3 3 3 3 --style 0 --gpu 6 1> /dev/null 2> /dev/null 
