#!/bin/bash
python3.5 ../main.py --dir loc/top -w 0.0 -s 1 0 1 0 1 0 1 0 --style 0 --gpu 4 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir loc/bot -w 0.0 -s 0 1 0 1 0 1 0 1 --style 0 --gpu 4 1> /dev/null 2> /dev/null