#!/bin/bash
python3.5 ../main.py --dir supervised/style/2 -w 1.0 -s 1 1 0 0 0 0 0 0 --style 2 --gpu 0 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir supervised/style/4 -w 1.0 -s 1 1 1 1 0 0 0 0 --style 4 --gpu 0 1> /dev/null 2> /dev/null