#!/bin/bash
python3.5 ../main.py --dir type/0 -w 0.0 -s 0 0 0 0 0 0 0 0 --style 0 --gpu 5 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir type/1 -w 0.0 -s 1 1 1 1 1 1 1 1 --style 0 --gpu 5 1> /dev/null 2> /dev/null
