#!/bin/bash
python3.5 ../main.py --dir supervised/loc/1 -w 0.0 -s 1 1 0 0 0 0 0 0 --style 0 --gpu 2 1> /dev/null 2> /dev/null &&
python3.5 ../main.py --dir supervised/loc/2 -w 0.0 -s 0 0 1 1 0 0 0 0 --style 0 --gpu 2 1> /dev/null 2> /dev/null
