#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step4/3 -w 0.3 0.1 1 --norm False --epoch3 0 --epoch4 300 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step4/4 -w 0.4 0.1 1 --norm False --epoch3 0 --epoch4 300 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step4/5 -w 0.5 0.1 1 --norm False --epoch3 0 --epoch4 300 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step4/6 -w 0.6 0.1 1 --norm False --epoch3 0 --epoch4 300 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step4/7 -w 0.7 0.1 1 --norm False --epoch3 0 --epoch4 300 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step4/8 -w 0.8 0.1 1 --norm False --epoch3 0 --epoch4 300 --gpu 6 1> /dev/null 2> /dev/null