#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/1 -w 0.1 1 --norm True --epoch3 0 --epoch4 300 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/2 -w 0.2 1 --norm True --epoch3 0 --epoch4 300 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/3 -w 0.3 1 --norm True --epoch3 0 --epoch4 300 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/4 -w 0.4 1 --norm True --epoch3 0 --epoch4 300 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/5 -w 0.5 1 --norm True --epoch3 0 --epoch4 300 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/6 -w 0.6 1 --norm True --epoch3 0 --epoch4 300 --gpu 2 1> /dev/null 2> /dev/null