#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/110000 -w 1 0 1 1 0 0 1 0 0 0 0 0 0 1 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/110001 -w 1 0 1 1 0 0 1 0 0 0 0 1 0 1 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/110010 -w 1 0 1 1 0 0 1 0 0 0 1 0 0 1 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/110011 -w 1 0 1 1 0 0 1 0 0 0 1 1 0 1 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/110100 -w 1 0 1 1 0 0 1 0 0 1 0 0 0 1 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/110101 -w 1 0 1 1 0 0 1 0 0 1 0 1 0 1 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/110110 -w 1 0 1 1 0 0 1 0 0 1 1 0 0 1 --gpu 6 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/110111 -w 1 0 1 1 0 0 1 0 0 1 1 1 0 1 --gpu 6 1> /dev/null 2> /dev/null