#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo8entropy4lr50 -w 0.8 0.4 --noise-rate 0.6 --lr 0.50 --noise-type sym --gpu 7 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo8entropy4lr10 -w 0.8 0.4 --noise-rate 0.6 --lr 0.10 --noise-type sym --gpu 7 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo8entropy4lr5 -w 0.8 0.4 --noise-rate 0.6 --lr 0.05 --noise-type sym --gpu 7 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo8entropy4lr1 -w 0.8 0.4 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 7 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo8entropy8lr50 -w 0.8 0.8 --noise-rate 0.6 --lr 0.50 --noise-type sym --gpu 7 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo8entropy8lr10 -w 0.8 0.8 --noise-rate 0.6 --lr 0.10 --noise-type sym --gpu 7 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo8entropy8lr5 -w 0.8 0.8 --noise-rate 0.6 --lr 0.05 --noise-type sym --gpu 7 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo8entropy8lr1 -w 0.8 0.8 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 7 1> /dev/null 2> /dev/null