#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/101000 -w 1 0 1 0 1 0 1 0 0 0 0 0 0 1 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/101001 -w 1 0 1 0 1 0 1 0 0 0 0 1 0 1 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/101010 -w 1 0 1 0 1 0 1 0 0 0 1 0 0 1 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/101011 -w 1 0 1 0 1 0 1 0 0 0 1 1 0 1 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/101100 -w 1 0 1 0 1 0 1 0 0 1 0 0 0 1 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/101101 -w 1 0 1 0 1 0 1 0 0 1 0 1 0 1 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/101110 -w 1 0 1 0 1 0 1 0 0 1 1 0 0 1 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/101111 -w 1 0 1 0 1 0 1 0 0 1 1 1 0 1 --gpu 5 1> /dev/null 2> /dev/null