#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step3/2 -w 0.2 1 --norm False --epoch3 300 --epoch4 0 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step3/3 -w 0.3 1 --norm False --epoch3 300 --epoch4 0 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step3/4 -w 0.4 1 --norm False --epoch3 300 --epoch4 0 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step3/5 -w 0.5 1 --norm False --epoch3 300 --epoch4 0 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step3/6 -w 0.6 1 --norm False --epoch3 300 --epoch4 0 --gpu 4 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step3/7 -w 0.7 1 --norm False --epoch3 300 --epoch4 0 --gpu 4 1> /dev/null 2> /dev/null