#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo1entropy1lr50 -w 0.1 0.1 --noise-rate 0.6 --lr 0.50 --noise-type sym --gpu 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo1entropy1lr10 -w 0.1 0.1 --noise-rate 0.6 --lr 0.10 --noise-type sym --gpu 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo1entropy1lr5 -w 0.1 0.1 --noise-rate 0.6 --lr 0.05 --noise-type sym --gpu 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo1entropy1lr1 -w 0.1 0.1 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo1entropy2lr50 -w 0.1 0.2 --noise-rate 0.6 --lr 0.50 --noise-type sym --gpu 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo1entropy2lr10 -w 0.1 0.2 --noise-rate 0.6 --lr 0.10 --noise-type sym --gpu 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo1entropy2lr5 -w 0.1 0.2 --noise-rate 0.6 --lr 0.05 --noise-type sym --gpu 0 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Param/pseudo1entropy2lr1 -w 0.1 0.2 --noise-rate 0.6 --lr 0.01 --noise-type sym --gpu 0 1> /dev/null 2> /dev/null