#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/7 -w 0.7 1 --norm True --epoch3 0 --epoch4 300 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/8 -w 0.8 1 --norm True --epoch3 0 --epoch4 300 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/9 -w 0.9 1 --norm True --epoch3 0 --epoch4 300 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/10 -w 1.0 1 --norm True --epoch3 0 --epoch4 300 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step3/0 -w 0.0 1 --norm False --epoch3 300 --epoch4 0 --gpu 3 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/None/Step3/1 -w 0.1 1 --norm False --epoch3 300 --epoch4 0 --gpu 3 1> /dev/null 2> /dev/null