#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/1000 --t0 1 --t1 0 --t2 0 --t3 0 --gpu 0 1> /dev/null 2> /dev/null &
python3 ../main.py --dir /home/hhjung/hhjung/MEM/1001 --t0 1 --t1 0 --t2 0 --t3 1 --gpu 1 1> /dev/null 2> /dev/null &
python3 ../main.py --dir /home/hhjung/hhjung/MEM/1010 --t0 1 --t1 0 --t2 1 --t3 0 --gpu 2 1> /dev/null 2> /dev/null &
python3 ../main.py --dir /home/hhjung/hhjung/MEM/1011 --t0 1 --t1 0 --t2 1 --t3 1 --gpu 3 1> /dev/null 2> /dev/null &
python3 ../main.py --dir /home/hhjung/hhjung/MEM/1100 --t0 1 --t1 1 --t2 0 --t3 0 --gpu 4 1> /dev/null 2> /dev/null &
python3 ../main.py --dir /home/hhjung/hhjung/MEM/1101 --t0 1 --t1 1 --t2 0 --t3 1 --gpu 5 1> /dev/null 2> /dev/null &
python3 ../main.py --dir /home/hhjung/hhjung/MEM/1110 --t0 1 --t1 1 --t2 1 --t3 0 --gpu 6 1> /dev/null 2> /dev/null &
python3 ../main.py --dir /home/hhjung/hhjung/MEM/1111 --t0 1 --t1 1 --t2 1 --t3 1 --gpu 7 1> /dev/null 2> /dev/null