#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/010000 -w 1 0 0 1 0 0 1 0 0 0 0 0 0 1 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/010001 -w 1 0 0 1 0 0 1 0 0 0 0 1 0 1 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/010010 -w 1 0 0 1 0 0 1 0 0 0 1 0 0 1 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/010011 -w 1 0 0 1 0 0 1 0 0 0 1 1 0 1 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/010100 -w 1 0 0 1 0 0 1 0 0 1 0 0 0 1 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/010101 -w 1 0 0 1 0 0 1 0 0 1 0 1 0 1 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/010110 -w 1 0 0 1 0 0 1 0 0 1 1 0 0 1 --gpu 2 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/010111 -w 1 0 0 1 0 0 1 0 0 1 1 1 0 1 --gpu 2 1> /dev/null 2> /dev/null