#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step3/6 -w 0.6 1 --norm True --epoch3 300 --epoch4 0 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step3/7 -w 0.7 1 --norm True --epoch3 300 --epoch4 0 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step3/8 -w 0.8 1 --norm True --epoch3 300 --epoch4 0 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step3/9 -w 0.9 1 --norm True --epoch3 300 --epoch4 0 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step3/10 -w 1.0 1 --norm True --epoch3 300 --epoch4 0 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Norm/Step4/0 -w 0.0 1 --norm True --epoch3 0 --epoch4 300 --gpu 1 1> /dev/null 2> /dev/null