#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.4/Step4/6 -w 0.6 1 --noise-rate 0.4 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.4/Step4/7 -w 0.7 1 --noise-rate 0.4 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.4/Step4/8 -w 0.8 1 --noise-rate 0.4 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.4/Step4/9 -w 0.9 1 --noise-rate 0.4 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.4/Step4/10 -w 1.0 1 --noise-rate 0.4 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/1 -w 0.1 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/2 -w 0.2 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/3 -w 0.3 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/4 -w 0.4 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/5 -w 0.5 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/6 -w 0.6 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/7 -w 0.7 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/8 -w 0.8 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/9 -w 0.9 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/Sym0.6/Step4/10 -w 1.0 1 --noise-rate 0.6 --noise-type sym --epoch3 0 --epoch4 300 --gpu 5 1> /dev/null 2> /dev/null 