#!/bin/bash
python3 ../main.py --dir /home/hhjung/hhjung/MEM/001000 -w 1 0 0 0 1 0 1 0 0 0 0 0 0 1 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/001001 -w 1 0 0 0 1 0 1 0 0 0 0 1 0 1 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/001010 -w 1 0 0 0 1 0 1 0 0 0 1 0 0 1 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/001011 -w 1 0 0 0 1 0 1 0 0 0 1 1 0 1 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/001100 -w 1 0 0 0 1 0 1 0 0 1 0 0 0 1 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/001101 -w 1 0 0 0 1 0 1 0 0 1 0 1 0 1 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/001110 -w 1 0 0 0 1 0 1 0 0 1 1 0 0 1 --gpu 1 1> /dev/null 2> /dev/null &&
python3 ../main.py --dir /home/hhjung/hhjung/MEM/001111 -w 1 0 0 0 1 0 1 0 0 1 1 1 0 1 --gpu 1 1> /dev/null 2> /dev/null